In [1]:
import numpy as np
import math

In [10]:
mine=np.array([[2,1,0],[2,0,0],[2,1,2]])
np.less(mine,1).sum(axis=1)

array([1, 2, 0])

In [21]:
thing = np.array([.001,.001,.001,.001,0])
(np.arange(5)*(1-thing)).sum()/(5-thing.sum())

2.0004003202562046

In [71]:
index=np.arange(64)
temp_r=np.random.rand(64)/600
temp= temp_r.sum()
(index*(1-temp_r)).sum()/(64-temp)

31.498869617968484

In [2]:
base_grid=np.linspace(-7.96875,7.96875,64)
base_grid= base_grid.repeat(64)
base_grid=base_grid.reshape((64,64))
base_grid=np.stack((base_grid,base_grid.transpose()),axis=2)
r=np.sqrt(np.square(base_grid).sum(axis=2))
base_grid=np.append(base_grid,np.expand_dims(r,2),axis=2)

def activation_type(matrix, kind):
    if kind<-0.5:
        return np.sin(matrix)
    elif kind<0.0:
        return np.cos(matrix)
    elif kind<.5:
        return np.exp((np.square(matrix/2)/-2))/(2*(2*math.pi)**.5)
    return matrix

def run_cppn(sol):
    h=np.matmul(base_grid,sol[0:12].reshape((3,4))*2)
    h0=activation_type(h[:,:,0],sol[27])
    h1=activation_type(h[:,:,1],sol[28])
    h2=activation_type(h[:,:,2],sol[29])
    h3=activation_type(h[:,:,3],sol[30])
    h = np.stack((h0,h1,h2,h3),axis=2)
    h=np.matmul(h,sol[12:24].reshape((4,3))*2)
    h0=activation_type(h[:,:,0],sol[31])
    h1=activation_type(h[:,:,1],sol[32])
    h2=activation_type(h[:,:,2],sol[33])
    h = np.stack((h0,h1,h2),axis=2)
    h=np.matmul(h,sol[24:27].reshape((3,1))*2)
    return 1/(1 + np.exp(-h))


goal = run_cppn(np.random.rand(34)*2-1)

In [29]:
index=np.expand_dims(np.arange(64), axis=1)
sol=run_cppn(np.random.rand(34)*2-1)
temp_r=np.square((goal-sol)).sum(axis=0)
temp= temp_r.sum()
m=np.max(temp_r)
(index*(m-temp_r)).sum()/(64*m-temp)

32.88217710005588

In [9]:
(m-temp_r)

array([[3.14434513],
       [3.53438794],
       [3.99789407],
       [4.34162263],
       [4.40598532],
       [4.14013198],
       [2.5999565 ],
       [2.62608059],
       [3.34809588],
       [4.02975479],
       [4.43860407],
       [4.41297191],
       [4.62101527],
       [3.97607751],
       [2.57552952],
       [3.06587808],
       [2.0037286 ],
       [2.02609091],
       [4.31465481],
       [5.47048928],
       [5.31887154],
       [4.26187896],
       [2.90992107],
       [3.24837724],
       [4.5125963 ],
       [5.15671223],
       [4.35036897],
       [2.66860028],
       [1.46040587],
       [2.05139287],
       [4.23291536],
       [4.54792815],
       [2.87427464],
       [1.39042318],
       [1.12117866],
       [1.51108722],
       [2.25296752],
       [2.92137729],
       [2.62407046],
       [1.12593443],
       [0.        ],
       [0.5429693 ],
       [2.10240199],
       [3.47341352],
       [3.96484181],
       [4.88966897],
       [6.26186907],
       [5.303

In [10]:
m

8.295603590095922

In [11]:
64*m-temp

224.2643891198553

In [12]:
(m-temp_r).sum()

224.2643891198553

In [13]:
index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [14]:
(index*(m-temp_r))

array([[  0.        ,   3.14434513,   6.28869027, ..., 191.80505308,
        194.94939822, 198.09374335],
       [  0.        ,   3.53438794,   7.06877589, ..., 215.59766456,
        219.1320525 , 222.66644045],
       [  0.        ,   3.99789407,   7.99578814, ..., 243.87153829,
        247.86943236, 251.86732643],
       ...,
       [  0.        ,   5.10418162,  10.20836325, ..., 311.35507898,
        316.4592606 , 321.56344222],
       [  0.        ,   5.51670886,  11.03341771, ..., 336.51924022,
        342.03594907, 347.55265793],
       [  0.        ,   4.55201047,   9.10402094, ..., 277.67263869,
        282.22464916, 286.77665963]])